[package]
name = "pbcodec"
version = "0.0.1"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
description = "An asynchronous encoder/decoder for Protocol Buffers"
homepage = "https://github.com/sile/pdcodec"
repository = "https://github.com/sile/pdcodec"
readme = "README.md"
keywords = []
categories = []
license = "MIT"

[badges]
travis-ci = {repository = "sile/pdcodec"}
codecov = {repository = "sile/pdcodec"}

[dependencies]
byteorder = "1"
futures = "0.1"
trackable = "0.2"
